#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_partcloud = env_modules.Clone()

# Godot source files
module_obj = []
env_partcloud.add_source_files(module_obj, "*.cpp")
env_partcloud.add_source_files(module_obj, "editor/*.cpp")
env.modules_sources += module_obj
